import { createReducer } from "@reduxjs/toolkit";
import parking1 from "../../images/parking1.jpg";
import parking2 from "../../images/parking2.jpg";
import parking3 from "../../images/parking3.jpg";
import parking4 from "../../images/parking4.jpg";
import parking5 from "../../images/parking5.jpg";
import parking6 from "../../images/parking6.jpg";
import parking7 from "../../images/parking7.jpg";
import parking8 from "../../images/parking8.jpg";
import parking9 from "../../images/parking9.jpg";
import parking10 from "../../images/parking10.jpg";
import parking11 from "../../images/parking11.jpg";
import parking12 from "../../images/parking12.jpg";
import parking13 from "../../images/parking13.jpg";
import parking14 from "../../images/parking14.jpg";
import parking15 from "../../images/parking15.jpg";
import parking16 from "../../images/parking16.jpg";
import parking17 from "../../images/parking17.jpg";
import parking18 from "../../images/parking18.jpg";

const initialState = {
  parking_data: [
    {
      name: "Central Parking",
      title: "parking",
      total_slots: 500,
      booked_slots: 150,
      description: "The most convenient parking in town",
      pic: "https://www.example.com/central-parking.jpg",
      city: "New York",
      country: "USA",
      area: "Broadway",
      pic: parking1,
      price: 5,
    },
    {
      name: "Downtown Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 80,
      description: "24/7 secure parking",
      pic: "https://www.example.com/downtown-parking.jpg",
      city: "London",
      country: "UK",
      area: "Oxford Street",
      pic: parking2,
      price: 5,
    },
    {
      name: "Eiffel Tower Parking",
      title: "parking",
      total_slots: 400,
      booked_slots: 120,
      description: "Free charging for electric cars",
      pic: "https://www.example.com/eiffel-tower-parking.jpg",
      city: "Paris",
      country: "France",
      area: "Champs-Élysées",
      pic: parking3,
      price: 5,
    },
    {
      name: "Airport Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 60,
      description: "Convenient location near the airport",
      pic: "https://www.example.com/airport-parking.jpg",
      city: "Tokyo",
      country: "Japan",
      area: "Haneda",
      pic: parking4,
      price: 5,
    },
    {
      name: "Harbour Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 50,
      description: "Affordable hourly rates",
      pic: "https://www.example.com/harbour-parking.jpg",
      city: "Sydney",
      country: "Australia",
      area: "Circular Quay",
      pic: parking5,
      price: 5,
    },
    {
      name: "Hollywood Parking",
      title: "parking",
      total_slots: 350,
      booked_slots: 100,
      description: "On-site car wash and detailing",
      pic: "https://www.example.com/hollywood-parking.jpg",
      city: "Los Angeles",
      country: "USA",
      area: "Hollywood Boulevard",
      pic: parking6,
      price: 5,
    },
    {
      name: "Vegas Parking",
      title: "parking",
      total_slots: 250,
      booked_slots: 70,
      description: "Valet parking available",
      pic: "https://www.example.com/vegas-parking.jpg",
      city: "Las Vegas",
      country: "USA",
      area: "The Strip",
      pic: parking7,
      price: 5,
    },
    {
      name: "Dubai Parking",
      title: "parking",
      total_slots: 500,
      booked_slots: 200,
      description: "Ample parking for large events",
      pic: "https://www.example.com/dubai-parking.jpg",
      city: "Dubai",
      country: "UAE",
      area: "Dubai World Trade Centre",
      pic: parking8,
      price: 5,
    },
    {
      name: "Amsterdam Parking",
      title: "parking",
      total_slots: 100,
      booked_slots: 30,
      description: "Secure bicycle parking",
      pic: "https://www.example.com/amsterdam-parking.jpg",
      city: "Amsterdam",
      country: "Netherlands",
      area: "Dam Square",
      pic: parking9,
      price: 5,
    },
    {
      name: "Sunset Strip Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 50,
      description: "Covered parking with EV charging stations",
      pic: "https://www.example.com/sunset-strip-parking.jpg",
      city: "Los Angeles",
      country: "USA",
      area: "Sunset Strip",
      pic: parking10,
      price: 5,
    },
    {
      name: "Waterfront Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 40,
      description: "Scenic views of the harbor",
      pic: "https://www.example.com/waterfront-parking.jpg",
      city: "Seattle",
      country: "USA",
      area: "Pier 66",
      pic: parking11,
      price: 5,
    },
    {
      name: "Times Square Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 100,
      description: "Convenient location for Broadway shows",
      pic: "https://www.example.com/times-square-parking.jpg",
      city: "New York",
      country: "USA",
      area: "Times Square",
      pic: parking12,
      price: 5,
    },
    {
      name: "Queen Street Parking",
      title: "parking",
      total_slots: 400,
      booked_slots: 150,
      description: "24/7 security monitoring",
      pic: "https://www.example.com/queen-street-parking.jpg",
      city: "Toronto",
      country: "Canada",
      area: "Queen Street West",
      pic: parking13,
      price: 5,
    },
    {
      name: "Golden Gate Parking",
      title: "parking",
      total_slots: 250,
      booked_slots: 80,
      description: "Close to popular tourist attractions",
      pic: "https://www.example.com/golden-gate-parking.jpg",
      city: "San Francisco",
      country: "USA",
      area: "Golden Gate Park",
      pic: parking14,
      price: 5,
    },
    {
      name: "Kensington Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 90,
      description: "Spacious parking for large vehicles",
      pic: "https://www.example.com/kensington-parking.jpg",
      city: "London",
      country: "UK",
      area: "Kensington High Street",
      pic: parking15,
      price: 5,
    },
    {
      name: "Champs-Elysees Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 70,
      description: "Free bicycle parking",
      pic: "https://www.example.com/champs-elysees-parking.jpg",
      city: "Paris",
      country: "France",
      area: "Champs-Élysées",
      pic: parking16,
      price: 5,
    },
    {
      name: "Shibuya Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 40,
      description: "Convenient location for shopping and dining",
      pic: "https://www.example.com/shibuya-parking.jpg",
      city: "Tokyo",
      country: "Japan",
      area: "Shibuya",
      pic: parking17,
      price: 5,
    },
    {
      name: "The Rocks Parking",
      title: "parking",
      total_slots: 100,
      booked_slots: 30,
      description: "Historic parking in the heart of the city",
      pic: "https://www.example.com/the-rocks-parking.jpg",
      city: "Sydney",
      country: "Australia",
      area: "The Rocks",
      pic: parking18,
      price: 5,
    },
    {
      name: "Central Parking",
      title: "parking",
      total_slots: 500,
      booked_slots: 150,
      description: "The most convenient parking in town",
      pic: "https://www.example.com/central-parking.jpg",
      city: "New York",
      country: "USA",
      area: "Broadway",
      pic: parking1,
      price: 5,
    },
    {
      name: "Downtown Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 80,
      description: "24/7 secure parking",
      pic: "https://www.example.com/downtown-parking.jpg",
      city: "London",
      country: "UK",
      area: "Oxford Street",
      pic: parking2,
      price: 5,
    },
    {
      name: "Eiffel Tower Parking",
      title: "parking",
      total_slots: 400,
      booked_slots: 120,
      description: "Free charging for electric cars",
      pic: "https://www.example.com/eiffel-tower-parking.jpg",
      city: "Paris",
      country: "France",
      area: "Champs-Élysées",
      pic: parking3,
      price: 5,
    },
    {
      name: "Airport Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 60,
      description: "Convenient location near the airport",
      pic: "https://www.example.com/airport-parking.jpg",
      city: "Tokyo",
      country: "Japan",
      area: "Haneda",
      pic: parking4,
      price: 5,
    },
    {
      name: "Harbour Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 50,
      description: "Affordable hourly rates",
      pic: "https://www.example.com/harbour-parking.jpg",
      city: "Sydney",
      country: "Australia",
      area: "Circular Quay",
      pic: parking5,
      price: 5,
    },
    {
      name: "Hollywood Parking",
      title: "parking",
      total_slots: 350,
      booked_slots: 100,
      description: "On-site car wash and detailing",
      pic: "https://www.example.com/hollywood-parking.jpg",
      city: "Los Angeles",
      country: "USA",
      area: "Hollywood Boulevard",
      pic: parking6,
      price: 5,
    },
    {
      name: "Vegas Parking",
      title: "parking",
      total_slots: 250,
      booked_slots: 70,
      description: "Valet parking available",
      pic: "https://www.example.com/vegas-parking.jpg",
      city: "Las Vegas",
      country: "USA",
      area: "The Strip",
      pic: parking7,
      price: 5,
    },
    {
      name: "Dubai Parking",
      title: "parking",
      total_slots: 500,
      booked_slots: 200,
      description: "Ample parking for large events",
      pic: "https://www.example.com/dubai-parking.jpg",
      city: "Dubai",
      country: "UAE",
      area: "Dubai World Trade Centre",
      pic: parking8,
      price: 5,
    },
    {
      name: "Amsterdam Parking",
      title: "parking",
      total_slots: 100,
      booked_slots: 30,
      description: "Secure bicycle parking",
      pic: "https://www.example.com/amsterdam-parking.jpg",
      city: "Amsterdam",
      country: "Netherlands",
      area: "Dam Square",
      pic: parking9,
      price: 5,
    },
    {
      name: "Sunset Strip Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 50,
      description: "Covered parking with EV charging stations",
      pic: "https://www.example.com/sunset-strip-parking.jpg",
      city: "Los Angeles",
      country: "USA",
      area: "Sunset Strip",
      pic: parking10,
      price: 5,
    },
    {
      name: "Waterfront Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 40,
      description: "Scenic views of the harbor",
      pic: "https://www.example.com/waterfront-parking.jpg",
      city: "Seattle",
      country: "USA",
      area: "Pier 66",
      pic: parking11,
      price: 5,
    },
    {
      name: "Times Square Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 100,
      description: "Convenient location for Broadway shows",
      pic: "https://www.example.com/times-square-parking.jpg",
      city: "New York",
      country: "USA",
      area: "Times Square",
      pic: parking12,
      price: 5,
    },
    {
      name: "Queen Street Parking",
      title: "parking",
      total_slots: 400,
      booked_slots: 150,
      description: "24/7 security monitoring",
      pic: "https://www.example.com/queen-street-parking.jpg",
      city: "Toronto",
      country: "Canada",
      area: "Queen Street West",
      pic: parking13,
      price: 5,
    },
    {
      name: "Golden Gate Parking",
      title: "parking",
      total_slots: 250,
      booked_slots: 80,
      description: "Close to popular tourist attractions",
      pic: "https://www.example.com/golden-gate-parking.jpg",
      city: "San Francisco",
      country: "USA",
      area: "Golden Gate Park",
      pic: parking14,
      price: 5,
    },
    {
      name: "Kensington Parking",
      title: "parking",
      total_slots: 300,
      booked_slots: 90,
      description: "Spacious parking for large vehicles",
      pic: "https://www.example.com/kensington-parking.jpg",
      city: "London",
      country: "UK",
      area: "Kensington High Street",
      pic: parking15,
      price: 5,
    },
    {
      name: "Champs-Elysees Parking",
      title: "parking",
      total_slots: 200,
      booked_slots: 70,
      description: "Free bicycle parking",
      pic: "https://www.example.com/champs-elysees-parking.jpg",
      city: "Paris",
      country: "France",
      area: "Champs-Élysées",
      pic: parking16,
      price: 5,
    },
    {
      name: "Shibuya Parking",
      title: "parking",
      total_slots: 150,
      booked_slots: 40,
      description: "Convenient location for shopping and dining",
      pic: "https://www.example.com/shibuya-parking.jpg",
      city: "Tokyo",
      country: "Japan",
      area: "Shibuya",
      pic: parking17,
      price: 5,
    },
    {
      name: "The Rocks Parking",
      title: "parking",
      total_slots: 100,
      booked_slots: 30,
      description: "Historic parking in the heart of the city",
      pic: "https://www.example.com/the-rocks-parking.jpg",
      city: "Sydney",
      country: "Australia",
      area: "The Rocks",
      pic: parking18,
      price: 5,
    },
  ],
};

export const Parking_Static_Data = createReducer(initialState, {
  setparkingdata: (state, action) => {
    state.parking_data = action.payload;
  },
});
