export const hotelsHeader = [
  { field: "id", headerName: "ID", width: 130 },
  { field: "image", headerName: "Image", width: 130 },
  { field: "name", headerName: "Name", width: 130 },
  { field: "type", headerName: "Type", width: 130 },
  { field: "surname", headerName: "Surname", width: 130 },
  { field: "mobile", headerName: "Mobile", width: 130 },
  { field: "addressLine1", headerName: "addressLine1", width: 130 },
  { field: "addressLine2", headerName: "addressLine2", width: 130 },
  { field: "postalCode", headerName: "Postal Code", width: 130 },
  { field: "state", headerName: "State", width: 130 },
  { field: "area", headerName: "Area", width: 130 },
  { field: "email", headerName: "Email", width: 130 },
  { field: "education", headerName: "Education", width: 130 },
  { field: "country", headerName: "Country", width: 130 },
  { field: "region", headerName: "Region", width: 130 },
];
